tmpDirectory: "D:/tmp"
sparkHome:  "D:/spark-2.4.1-bin-hadoop2.7"
mavenProperties:
  - url: "https://gitlab.com/api/v4/projects/25819110/packages/maven"
    privateToken: "B8UxzhjZiBDJK51ZVHxY"
    type: "gitlab"
nifiProperties:
  host: "http://localhost:8080"
gitProperties:
  - url: "https://gitlab.com/c2cc1/command-centre.git"
    token: "B8UxzhjZiBDJK51ZVHxY"
hadoopYarnProperties:
  coreSite : C:\Users\YSJ\.c2\core-site.xml
  hdfsSite : C:\Users\YSJ\.c2\hdfs-site.xml
  yarnSite : C:\Users\YSJ\.c2\yarn-site.xml
  webHdfsHost: "http://localhost:9001"
  yarnHost:
    - "http://localhost:8088"
    - "http://localhost:8088"
  username: "YSJ"
sparkCheckpointProperties:
  kafkaProperties:
    kafkaHosts:
      - "http://localhost:9092"
  webHdfsProperties:
    webHdfsHost: "http://localhost:9001"
    username: "YSJ"
  backupDirectory: "/user/YSJ/checkpointBackup"