kafkahosts:
- localhost:9092
jobs:
- job: app1
  checkpoint: checkpoint/app1
  startingOffsets: latest
  kafkaTopic:
  - test
- job: app2
  checkpoint: checkpoint/app2
  startingOffsets: latest
  kafkaTopic:
    - test