kafkahosts:
- localhost:9092
jobs:
- job: app1
  checkpoint: checkpoint1/app1
  startingOffsets: latest
  kafkaTopic:
    - test
    - test1
- job: app2
  checkpoint: checkpoint/app2
  startingOffsets: latest
  kafkaTopic:
    - test2
    - test