FROM node:15.12.0

RUN yarn -version
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY node_modules /usr/src/app/node_modules
COPY package*.json /usr/src/app/
COPY ".next" /usr/src/app/.next
COPY public /usr/src/app/public

EXPOSE 3000
CMD ["yarn","start"]